### ISSUE TITLE
Change imports from /dist to index.js in root for npm packages

### ISSUE THREAD

**Issue by Divide-By-0** [zkemail/zk-email-verify#101]
> We need to cleanup the helpers package etc so these imports can come from the root!

> You are importing from @zk-email/helpers/src  which is the .ts code - to transpile ts code in node_modules we would need additional config

> You can change the import to /dist - import { toCircomBigIntBytes } from "@zk-email/helpers/dist/binaryFormat";

**Comment by isidroamv** [comment]
I believe it would be ideal import the modules in the format:

`import { toCircomBigIntBytes } from "@zk-email/helpers/binaryFormat";` instead of
`import { toCircomBigIntBytes } from "@zk-email/helpers/dist/binaryFormat";`

As long we export the functions from `index.ts` from the root and `index.js` from the `dist` the functions should be accesible from both.

@Divide-By-0

**Comment by isidroamv** [comment]
Or even better:

`import { toCircomBigIntBytes } from "@zk-email/helpers";`

**Comment by Divide-By-0** [comment]
> Or even better:
> 
> `import { toCircomBigIntBytes } from "@zk-email/helpers";`

Absolutely! Metachaser's original docs pr tried to do this but our tests were super broken then.

**Comment by Metachaser24** [comment]
@isidroamv this is done right?

**Comment by isidroamv** [comment]
> @isidroamv this is done right?

Yes, this was completed on the PR https://github.com/zkemail/zk-email-verify/pull/153
